// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rofemykesyznvyahdcdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvZmVteWtlc3l6bnZ5YWhkY2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDExMjUsImV4cCI6MjA2MTI3NzEyNX0.If-Xvhv_XWuHx58X0gcKq6wFChG6jqXJUClf6Nl7Hfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);